build:
	mvn package docker:build)
run:
	sudo docker run -p 8080:8080 -t ciberacademy/ciber-mangekamp --name ciber-mangekamp
stop:
	sudo docker stop ciber-mangekamp
clean:
	sudo docker rm ciber-mangekamp
